version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: prathomwiky
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql/prathomwiky.sql:/docker-entrypoint-initdb.d/prathomwiky.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha-dark
      
  express:
    build: .
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
    ports:
      - "${PORT}:${PORT}"
