version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: prathomwiky
      POSTGRES_USER: adminer
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql/prathomwiky.sql:/docker-entrypoint-initdb.d/prathomwiky.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
